version: "3.8"  # !

services:
  nginx:
    build: requirements/nginx/.
    image: nginx:v1
    container_name: nginx
    env_file:
      .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      - incep_network
    restart:
      always
  

  wordpress:
    build: requirements/wordpress/.
    image: wordpress:v1
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - ./web:/var/www/html
    networks:
      - incep_network
    restart:
      always

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb:v1
    volumes:
      - ../mariadb_storage:/var/lib/mysql
    networks:
      - incep_network
    env_file:
      - .env
    ports:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10


networks:
  incep_network:
    driver: bridge
    name: incep_network  # Set the network name explicitly
